### PR TITLE
export and document shoot

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
I plan to use this method in a lesson and it would remove a bit of overhead if it were exported and documented

### CODE REVIEW

**Comment by BeastyBlacksmith** [comment]
what are the units for windspeed and weight?

**Comment by BeastyBlacksmith** [comment]
Just bumped into this while teaching the lesson. @Roboneet could this be merged or are there objections?

**Comment by BeastyBlacksmith** [comment]
bump

**Comment by DhairyaLGandhi** [comment]
Lgtm, `shoot` is hopefully specific enough that it is fine too export to

**Pull request merged**
